### ISSUE TITLE
Unable to find mixin

### ISSUE THREAD

**Issue by Rasarts** [dart-lang/custom-element-apigen#46]
Hi. I have new trouble to port [polymer element](https://github.com/Rasarts/wysiwyg-e/tree/base). When I run:
`pub run custom_element_apigen:update gen.yaml`

I get unhandled exception:
`3 of 9: lib/src/wysiwyg-e/tools/blockquote.html   Unhandled exception:
Unable to find mixin WYSIWYG.ToolBehavior. Make sure the mixin file is loaded.`

In gen.yaml I add this file to files_to_load section:
```
files_to_load:
    - lib/src/wysiwyg-e/wysiwyg-tool-behavior.html
files_to_generate:
    - wysiwyg-e/wysiwyg-tool-behavior.html
    - wysiwyg-e/wysiwyg-tool-styles.html

    - wysiwyg-e/tools/blockquote.html
```

What am I doing wrong?

**Comment by jakemac53** [comment]
It looks like the behavior implementation is missing the `@polymerBehavior` comment (see [here](https://github.com/Rasarts/wysiwyg-e/blob/base/lib/src/wysiwyg-e/wysiwyg-tool-behavior.html#L1)). It needs to have a comment like [this](https://github.com/PolymerElements/iron-behaviors/blob/master/iron-button-state.html#L17) so that hydrolysis can find the behavior.

**Comment by jakemac53** [comment]
Oh also you shouldn't need to relist it in `files_to_load`, anything in `files_to_generate` should get loaded. It was just unable to recognize the behavior at all.

**Comment by Rasarts** [comment]
Thanks you.
